[package]
name = "wwos"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
wwos_blob = { path = "../wwos_blob" }
wwmalloc = { path = "../wwmalloc" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(WWOS_BOARD, values("qemu_aarch64_virt9", "raspi4b"))'] }
